variables:
- name: 'environment'
  value: 'INF'
- name: 'terraform_folder'
  value: 'AVD'
- name: 'artifact_name'
  value: 'wvd_drop'
- name: 'client_id'
  value: ''
- name: 'tenant_id'
  value: ''


trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: "CopyFiles"
    steps:    
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)/$(terraform_folder)'
      inputs:
        SourceFolder: $(terraform_folder)
        TargetFolder: '$(build.artifactstagingdirectory)/$(terraform_folder)'
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: $(artifact_name)'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: $(artifact_name)

- stage: Terraform_Plan
  jobs:
  - job: "Terraform_Plan"
    steps:
      - checkout: none
        clean: true
        fetchDepth: 5
        lfs: true
        
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: '$(artifact_name)'
          downloadPath: '$(System.DefaultWorkingDirectory)'
        displayName: 'Download Artifact'

      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '1.2.2'
        displayName: 'Install Terraform'
                     
      
      - script: |
          az login --service-principal -u $(client_id) -p $(client_secret) --tenant $(tenant_id)  
        displayName: 'Login to Azure'  
      
      - script: |
          terraform init -backend-config="key=$(backend_key)"
        workingDirectory: $(System.DefaultWorkingDirectory)/$(artifact_name)/$(terraform_folder)
        displayName: 'Terraform Init'

      - script: |
          terraform plan -no-color -var="client_id=$(client_id)" -var="client_secret=$(client_secret)" -var="local_password=$(local_password)" -var="domain_password=$(domain_password)"
        workingDirectory: $(System.DefaultWorkingDirectory)/$(artifact_name)/$(terraform_folder)
        displayName: 'Terraform Plan'   

- stage: deploy
  jobs:
    - deployment: DeployTerraform
      displayName: Deploy to Azure
      environment: $(environment)
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: none
                clean: true
                fetchDepth: 5
                lfs: true

              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: '$(artifact_name)'
                  downloadPath: '$(System.DefaultWorkingDirectory)'
                displayName: 'Download Artifact'

              - task: TerraformInstaller@0
                inputs:
                  terraformVersion: '1.2.2'
                displayName: 'Install Terraform'
                                
                  
              - script: |
                  az login --service-principal -u $(client_id) -p $(client_secret) --tenant $(tenant_id)  
                displayName: 'Login to Azure'  
                
              - script: |
                  terraform init -backend-config="key=$(backend_key)"
                workingDirectory: $(System.DefaultWorkingDirectory)/$(artifact_name)/$(terraform_folder)
                displayName: 'Terraform Init'
              
              - script: |
                  terraform apply -auto-approve -var="client_id=$(client_id)" -var="domain_password=$(domain_password)" -var="local_password=$(local_password)" -var="client_secret=$(client_secret)"
                workingDirectory: $(System.DefaultWorkingDirectory)/$(artifact_name)/$(terraform_folder)
                displayName: 'Terraform Apply'

